version: 2

models:
  - name: std_customers
    columns:
      - name: account_id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: surname
        data_tests:
          - not_null
      - name: date_of_birth
        data_tests:
          - not_null
      - name: email
        data_tests:
          - not_null
      - name: street_number
        data_tests:
          - not_null
      - name: street_name
        data_tests:
          - not_null
      - name: post_town
        data_tests:
          - not_null
      - name: postcode
        data_tests:
          - not_null

  - name: dim_customers
    columns:
      - name: account_id
        data_tests:
          - unique
          - not_null

  - name: dim_address
    columns:
      - name: property_id
        data_tests:
          - unique
          - not_null

  - name: fct_interests
    columns:
      - name: uuid